"""create migration for freebie

Revision ID: 5c8d8a5974bb
Revises: 39df734cf5f8
Create Date: 2023-09-01 14:29:35.772206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8d8a5974bb'
down_revision = '39df734cf5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
