"""create migration for freebie

Revision ID: a0eb40e6880e
Revises: d80d6ec2bc00
Create Date: 2023-09-01 14:33:05.644697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0eb40e6880e'
down_revision = 'd80d6ec2bc00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
