"""create migration for freebie

Revision ID: a48ae4183e07
Revises: b20656ce8fd0
Create Date: 2023-09-01 19:06:49.709156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48ae4183e07'
down_revision = 'b20656ce8fd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
