"""create migration for freebie

Revision ID: b20656ce8fd0
Revises: a0eb40e6880e
Create Date: 2023-09-01 14:42:39.894559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20656ce8fd0'
down_revision = 'a0eb40e6880e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.drop_column('value')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
