"""create migration for freebie

Revision ID: d80d6ec2bc00
Revises: 5c8d8a5974bb
Create Date: 2023-09-01 14:30:20.237211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80d6ec2bc00'
down_revision = '5c8d8a5974bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
